# Generated by Django 3.2.13 on 2023-09-23 14:23

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_fullname', models.CharField(max_length=200)),
                ('taken', models.DateTimeField(verbose_name='attendance taken date')),
            ],
        ),
    ]
